patches:
  - mode: "append"
    file: "CMakeLists_template.txt"
    after: "add_executable"
    insert: "# 非侵入式引入头文件\ntarget_compile_options(${PROJECT_NAME}.elf PRIVATE -include ${CMAKE_SOURCE_DIR}/UserCode/app/app.h)"
    marker: "UserCode/app/app.h"
  - mode: "append"
    file: "Makefile"
    marker: "UserCode/app/app.h"
    after: "CFLAGS +="
    insert: "# 非侵入式引入头文件\nCFLAGS += -include UserCode/app/app.h"
  - mode: "replace"
    file: "CMakeLists_template.txt"
    find: "include_directories(${includes})"
    insert: "include_directories(${includes} UserCode)"
  - mode: "replace"
    file: "CMakeLists_template.txt"
    find: "file(GLOB_RECURSE SOURCES ${sources})"
    insert: "file(GLOB_RECURSE SOURCES ${sources} \"UserCode/*.*\")"